/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.11.0.396.4 */
/* Module Version: 5.7 */
/* Fri Oct 04 22:28:47 2024 */

/* parameterized module instance */
my_pll __ (.CLKI( ), .CLKOP( ), .CLKOS( ));
