/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.11.0.396.4 */
/* Module Version: 5.7 */
/* Sun Oct 27 17:48:11 2024 */

/* parameterized module instance */
PLL __ (.CLKI( ), .CLKOP( ));
