/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.11.0.396.4 */
/* Module Version: 5.7 */
/* Mon Oct 28 17:03:13 2024 */

/* parameterized module instance */
PLL_TX __ (.CLKI( ), .CLKOP( ));
