/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.14.0.75.2 */
/* Module Version: 1.6 */
/* Mon Oct 28 21:21:52 2024 */

/* parameterized module instance */
SinCos __ (.Clock( ), .ClkEn( ), .Reset( ), .Theta( ), .Sine( ), 
    .Cosine( ));
